version: '3.6'

services:
  structsd:
    image: 'structs/structsd:latest'
    hostname: 'structsd'
    restart: on-failure
    ports:
      - 26656:26656
      - 26657:26657
      - 1317:1317
    environment:
      MONIKER: 'UnknownGuild'
      NETWORK_VERSION: '00'
      NETWORK_TYPE: 'localtestnet'
      NETWORK_CHAIN_ID: 'structstestnet-00'
      NODE_TYPE: 'NONVALIDATING'
      NODE_INDEXER: 'psql'
      NODE_INDEXER_PG_CONNECTION: 'postgres://structs_indexer@structs-pg:5432/structs'
  structs-pg:
    image: 'structs/structs-pg:latest'
    hostname: 'structs-pg'
    ports:
      - 5432:5432
    restart: on-failure
  structs-proxy:
    image: 'structs/structs-proxy:latest'
    hostname: 'structs-proxy'
    restart: on-failure
    ports:
     - 80:80  
