version: '3.9'

x-common-env: &common-env
  STRUCTS_MONIKER: "${MONIKER}"
  STRUCTS_NETWORK_VERSION: "${NETWORK_VERSION}"
  STRUCTS_CHAIN_ID: "${NETWORK_CHAIN_ID}"

services:
  structsd-network-config:
    image: 'structs/structsd:latest'
    command: ["bash", "/root/scripts/network-config.sh"]
    volumes:
      - chaindata:/root/.structs
      - chainshare:/root/reactor_share
      - chainbackup:/root/reactor_backup
    environment:
      <<: *common-env
  structsd-reactor-config:
    image: 'structs/structsd:latest'
    command: ["bash", "/root/scripts/reactor-config.sh"]
    restart: on-failure
    volumes:
      - chaindata:/root/.structs
      - chainshare:/root/reactor_share
      - chainbackup:/root/reactor_backup
    depends_on:
      structsd-network-config:
        condition: service_completed_successfully
    environment:
      <<: *common-env
  structsd:
    image: 'structs/structsd:latest'
    hostname: 'structsd'
    volumes:
      - chaindata:/root/.structs
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "bash", "/root/scripts/health-check-sync-state.sh" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 48h
    depends_on:
      structsd-network-config:
        condition: service_completed_successfully
      structsd-reactor-config:
        condition: service_completed_successfully
    ports:
      - 26656:26656
      - 26657:26657
      - 1317:1317
    environment:
      <<: *common-env
  structsd-reactor-create:
    image: 'structs/structsd:latest'
    command: ["bash", "/root/scripts/reactor-create.sh"]
    restart: on-failure
    depends_on:
      structsd-network-config:
        condition: service_completed_successfully
      structsd-reactor-config:
        condition: service_completed_successfully
      structsd:
        condition: service_healthy
    volumes:
      - chainshare:/root/reactor_share
    environment:
      <<: *common-env
      STRUCTS_GUILD_MNEMONIC: "${GUILD_MNEMONIC}"
      STRUCTS_VALIDATOR_INITIAL_STAKING_AMOUNT: "${VALIDATOR_INITIAL_STAKING_AMOUNT}"
      STRUCTS_VALIDATOR_IDENTITY: "${VALIDATOR_IDENTITY}"
      STRUCTS_GUILD_WEBSITE: "${GUILD_WEBSITE}"
      STRUCTS_GUILD_CONTACT: "${GUILD_CONTACT}"
      STRUCTS_VALIDATOR_COMMISSION_RATE: "${VALIDATOR_COMMISSION_RATE}"
      STRUCTS_VALIDATOR_MAX_RATE: "${VALIDATOR_MAX_RATE}"
      STRUCTS_VALIDATOR_MAX_CHANGE_RATE: "${VALIDATOR_MAX_CHANGE_RATE}"
      STRUCTS_VALIDATOR_MIN_SELF_DELEGATION: "${VALIDATOR_MIN_SELF_DELEGATION}"
volumes:
  chaindata:
    name: structsd-chaindata
  chainshare:
    name: structsd-chainshare
  chainbackup:
    name: structsd-chainbackup


